### ISSUE TITLE
ROS2 interface for the RoadNetwork

### ISSUE THREAD

**Issue by agalbachicar** [maliput/ros2_maliput#1]
## Desired behavior

Provide a ROS2 interface for the maliput::api::RoadNetwork.

The following is a list of characteristics we want:

- It must be a query - response via ROS2 services.
- It must be able to load RoadNetworks by means of ROS parameters (YAML description) or via a service call as well.
- It must be a component, and provide some launchfiles for easy use and integration into other systems.
- There must be an executable to trigger with `ros2 run`
- A data translation layer is desired to make this query entity as reusable as possible for future integrations.

## Implementation suggestion

The following suggests a feature complete list of tasks.

- [ ] Create a package for messages in which we start by migrating the maliput types into it. #2
  - [x] Types for RoadGeometry, BranchPoint, Junction, Segment and Lane queries. #3  
  - [ ] Types for RoadRulebook and RuleRegistry.
  - [ ] Types for Phases and friends.
  - [ ] Types for Intersections.
  - [ ] Types for other misc. entities (object API and so on).
- [ ] Create the translation layer: from maliput types into ros messages and vice versa.
  - [x] Translate types for RoadGeometry, BranchPoint, Junction, Segment and Lane queries. #4 #5 #6
  - [ ] Translate types for RoadRulebook and RuleRegistry.
  - [ ] Translate types for Phases and friends.
  - [ ] Translate types for Intersections.
  - [ ] Translate types for other misc. entities  (object API and so on).
- [ ] Load a RoadNetwork from a set of parameters
  - [x] Build a Node that parses the arguments and loads a RoadNetworkPlugin. #7 #8
  - [ ] Provide a lauchfile and a few yaml sample configurations. #8
  - [ ] Provide a ROS2 executable.
- [ ] Provide API coverage:
  - [x] Provide coverage to the RoadGeometry and other friend entities. #8 #10 #14 #15 #16 #17 #18 #19 #20 #21
  - [ ] Provide coverage to the RoadRulebook and RuleRegistry, and other friend entities.
  - [ ] Provide coverage to the Phases and other friend entities.
  - [ ] Provide coverage to the Intersections.
  - [ ] Provide coverage to other misc. entities (object API and so on).

## Additional context

This is a required interface to enable multi-agent simulation with ROS2 based systems that will help to spread the use of maliput with other development environments.

**Comment by agalbachicar** [comment]
Some design comments after talking with @francocipollone : 

- To load RoadNetworks, use [CreateRoadNetwork()](https://github.com/maliput/maliput/blob/main/include/maliput/plugin/create_road_network.h#L41-L50) function from the plugin interface as it hides all the unnecessary complexity.
- To load the parameters that will end up being a std::map<string,string> as a second argument of the aforementioned function, the best thing is to clone the recent [implementation from maliput_viz](https://github.com/maliput/maliput_viz/blob/main/src/maliput_viz/tools/yaml_parser.h).
- We should better keep two entities separated:
  - MaliputQuery which is a class that will manage the direct and high level queries to the RoadNetwork.  
  - MaliputRosNode which is a proper ROS2 node that will follow the style of ROS2 in terms of API, lifecycle and error management and reporting. Initially, we will inject a MaliputQuery into a MaliputRosNode. We will manage the impendance mismatch between the maliput and the ROS2 world within the node class.

**Comment by agalbachicar** [comment]
MaliputRosNode must subclass rclcpp_lifecycle::LifecycleNode to properly manage initialization and further node management as a component. Some links for future reference:

- http://design.ros2.org/articles/node_lifecycle.html
- https://docs.ros.org/en/galactic/Concepts/About-Composition.html
- https://docs.ros.org/en/galactic/How-To-Guides/Launching-composable-nodes.html

**Comment by agalbachicar** [comment]
I think this first milestone of having the RoadGeometry and some basic routing support is enough to test it with some integration examples with agents before proceeding and iterating on something more complex with the rules.
